import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import type { Connection } from '@xyflow/react';
import { api, dependencies, downloadArtifact, pretty, type Circuit, type Configuration, type GateNode, type Job, type Json, type RunArtifact, type RunEvent, type Scenario, type ScenarioDetail, type Signal } from './api';
import Graph, { TruthBadge, kindLabels } from './Graph';
import { nodeExecutions } from './execution';

const variantLabel: Record<string, string> = { normal: '正常路徑', missing: '資料缺失', conflict: '反例／衝突', fault: '故障路徑', counterexample: '反例', 'public-source': '公開文獻', public: '公開文獻', stale: '資料過期', 'out-of-scope': '超出適用範圍', 'tight-budget': '成本限制', 'long-context': '不同上下文長度', 'privacy-evidence': '補充隱私證據', 'latency-failed': '延遲反例', replication: '合成重現', 'config-change': '設定變更', 'upstream-failure': '上游故障', 'timeout-after-applied': '已修復但回應逾時', 'verification-failed': '健康驗證失敗', 'execute-failed': '動作執行失敗', healthy: '服務正常', 'mixed-signals': '觀察衝突', 'low-energy': '能源不足', 'short-window': '時間不足', 'instrument-off': '儀器關閉', 'no-radio': '無傳輸儀器', 'extra-goal': '追加目標', 'ample-budget': '資源充足', 'exact-budget': '精確資源邊界', 'invalid-proposal': '無效提案', renamed: '物件改名', distractors: '干擾資訊', inhibitor: '抑制規則', alternative: '替代規則', reversible: '可逆規則', blocked: '轉換受阻', 'one-shot': '一個示例', 'new-family': '新規則家族' };
const modeLabel: Record<string, string> = { fixture: '離線範例 · Fixture', 'recorded-live': '已錄製模型回應', 'live-localjev': '本機 LocalJev', 'live-typesafe': 'TypeSafe 服務' };
const eventLabel: Record<string, string> = { run_started: '執行開始', node_completed: '節點完成', provider_started: '提出語意問題', provider_completed: '收到模型回應', provider_failed: '模型呼叫失敗', run_completed: '執行結束' };
const workflowLabel: Record<string, string> = { completed: '流程已完成', cancelled: '已取消', budget_exhausted: '預算耗盡' };
const sourceLabel: Record<string, string> = { synthetic: '合成資料', 'public-source': '公開來源', 'user-provided': '使用者提供', 'source-backed': '可追溯來源' };
const tabs = [{ id: 'workbench', label: '電路工作台', num: '01' }, { id: 'evidence', label: '證據與主張', num: '02' }, { id: 'compare', label: '分支比較', num: '03' }, { id: 'library', label: '執行庫', num: '04' }] as const;
type Tab = typeof tabs[number]['id'];
function short(id?: string) { return id ? id.slice(0, 12) : '—'; }
function date(value?: string) { return value ? new Date(value).toLocaleString('zh-TW', { hour12: false }) : '—'; }
function errorMessage(error: unknown) { return error instanceof Error ? error.message : String(error); }
function Message({ children, kind = 'info' }: { children: ReactNode; kind?: string }) { return <div className={`message ${kind}`} role={kind === 'error' ? 'alert' : 'status'}>{children}</div>; }
function Code({ value }: { value: unknown }) { return <pre className="code-block">{pretty(value)}</pre>; }
function Dialog({ open, onClose, title, children, wide = false }: { open: boolean; onClose: () => void; title: string; children: ReactNode; wide?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null); const source = useRef<HTMLElement | null>(null);
  useEffect(() => { if (open && !ref.current?.open) { source.current = document.activeElement as HTMLElement; ref.current?.showModal(); } else if (!open && ref.current?.open) { ref.current.close(); source.current?.focus(); } }, [open]);
  return <dialog ref={ref} className={wide ? 'wide-dialog' : ''} aria-label={title} onCancel={onClose} onClose={() => { onClose(); source.current?.focus(); }}><header className="dialog-head"><h2>{title}</h2><button onClick={onClose} aria-label={`關閉${title}`}>×</button></header>{children}</dialog>;
}

export default function App() {
  const [scenarios, setScenarios] = useState<Scenario[]>([]); const [config, setConfig] = useState<Configuration>();
  const [scenarioId, setScenarioId] = useState(''); const [variant, setVariant] = useState('normal'); const [seed, setSeed] = useState(42); const [draft, setDraft] = useState<ScenarioDetail>();
  const [mode, setMode] = useState('fixture'); const [tab, setTab] = useState<Tab>('workbench'); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [artifact, setArtifact] = useState<RunArtifact>(); const [parent, setParent] = useState<RunArtifact>();
  const [overrides, setOverrides] = useState<Record<string, unknown>>({}); const [pendingConstraints, setPendingConstraints] = useState(false);
  const [changeReason, setChangeReason] = useState(''); const [jobId, setJobId] = useState(''); const [events, setEvents] = useState<RunEvent[]>([]); const [running, setRunning] = useState(false);
  const [runs, setRuns] = useState<RunArtifact[]>([]); const [runSearch, setRunSearch] = useState(''); const [selected, setSelected] = useState(''); const [nodeSearch, setNodeSearch] = useState('');
  const [inspectorOpen, setInspectorOpen] = useState(false); const [inspectorPage, setInspectorPage] = useState('summary'); const [folded, setFolded] = useState(false); const [layoutKey, setLayoutKey] = useState(0);
  const [editor, setEditor] = useState<null | 'node' | 'add' | 'input' | 'evidence' | 'circuit'>(null); const [editorText, setEditorText] = useState(''); const [editorError, setEditorError] = useState('');
  const [connectFrom, setConnectFrom] = useState(''); const [connectTo, setConnectTo] = useState(''); const [compareId, setCompareId] = useState('');
  const [replaying, setReplaying] = useState(false); const [replayCursor, setReplayCursor] = useState(0); const [playing, setPlaying] = useState(false);
  const [maxCalls, setMaxCalls] = useState(12); const [maxTimeMs, setMaxTimeMs] = useState(30000); const [performanceResult, setPerformanceResult] = useState('');
  const fileInput = useRef<HTMLInputElement>(null); const latestScenario = useRef(0);
  const refreshRuns = useCallback(async () => { const all = await api<RunArtifact[]>('/runs'); setRuns(all); return all; }, []);
  const loadScenario = useCallback(async (id: string, v: string, s: number) => {
    const request = ++latestScenario.current; setLoading(true); setError('');
    try { const result = await api<ScenarioDetail>(`/scenarios/${encodeURIComponent(id)}?variant=${encodeURIComponent(v)}&seed=${s}`); if (request !== latestScenario.current) return; setDraft(result); setSelected(result.circuit.nodes[0]?.id ?? ''); setArtifact(undefined); setParent(undefined); setEvents([]); setReplaying(false); setPlaying(false); setChangeReason(''); setOverrides({}); setPendingConstraints(false); setLayoutKey(k => k + 1); }
    catch (e) { if (request === latestScenario.current) setError(errorMessage(e)); } finally { if (request === latestScenario.current) setLoading(false); }
  }, []);
  useEffect(() => {
    let active = true;
    Promise.all([api<Scenario[]>('/scenarios'), api<Configuration>('/config'), api<RunArtifact[]>('/runs')]).then(([items, cfg, saved]) => { if (!active) return; setScenarios(items); setConfig(cfg); setRuns(saved); if (items[0]) { setScenarioId(items[0].id); void loadScenario(items[0].id, 'normal', 42); } else setLoading(false); }).catch(e => { if (active) { setError(`無法連線本機服務：${errorMessage(e)}。請啟動研究工作台服務後重試。`); setLoading(false); } });
    return () => { active = false; };
  }, [loadScenario]);
  useEffect(() => {
    if (!jobId || !running) return;
    let cancelled = false; let timer: ReturnType<typeof setTimeout>;
    async function poll() { try { const job = await api<Job>(`/jobs/${jobId}`); if (cancelled) return; setEvents(job.events ?? []); if (job.status !== 'running') { setRunning(false); if (job.artifact) { setArtifact(job.artifact); setParent(job.artifact); void refreshRuns(); } if (job.error) setError(job.error); setNotice(job.status === 'cancelled' ? '執行已取消；已完成的動作需以目的端查詢確認。' : '執行結束。請分別檢查流程結果與評測狀態。'); } else timer = setTimeout(poll, 250); } catch (e) { if (!cancelled) { setError(errorMessage(e)); setRunning(false); } } }
    void poll(); return () => { cancelled = true; clearTimeout(timer); };
  }, [jobId, running, refreshRuns]);
  useEffect(() => { if (!playing || !replaying) return; const timer = setInterval(() => setReplayCursor(n => { if (n >= events.length) { setPlaying(false); return n; } return n + 1; }), 600); return () => clearInterval(timer); }, [playing, replaying, events.length]);
  const shownEvents = replaying ? events.slice(0, replayCursor) : events;
  const signals = useMemo(() => { if (!replaying && artifact) return artifact.result.signals; const s: Record<string, Signal> = {}; for (const event of shownEvents) if (event.nodeId && event.signal) s[event.nodeId] = event.signal; return s; }, [artifact, replaying, shownEvents]);
  const node = draft?.circuit.nodes.find(n => n.id === selected); const nodeSignal = signals[selected]; const decision = artifact?.signals[selected];
  const scenario = scenarios.find(s => s.id === scenarioId); const isEdited = !!(draft && parent && (pretty(draft.circuit) !== pretty(parent.circuit) || pretty(draft.input) !== pretty(parent.input) || pretty(draft.evidence) !== pretty(parent.evidence)));
  const activeRequest = artifact?.requests.find(r => selected in r.questions); const selectedEvidence = draft?.evidence.filter(e => !decision?.evidenceIds.length || decision.evidenceIds.includes(e.evidenceId)) ?? [];
  const executionStates = useMemo(() => draft ? nodeExecutions(draft.circuit, signals, shownEvents) : {}, [draft?.circuit, signals, shownEvents]);
  const visibleNodes = draft?.circuit.nodes.filter(n => `${n.id} ${n.kind} ${n.kind === 'semantic' ? n.question.instructions : ''}`.toLowerCase().includes(nodeSearch.toLowerCase())) ?? [];
  const baseline = runs.find(r => r.runId === compareId) ?? runs.find(r => r.runId === artifact?.parentRunId);
  const modeAvailable = mode === 'fixture' || mode === 'live-localjev' && config?.localjev.available || mode === 'live-typesafe' && config?.typesafe.available;
  async function guarded(action: () => Promise<void>) { setError(''); setBusy(true); try { await action(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  function selectNode(id: string) { if (id.startsWith('group:')) { setFolded(false); setNotice('已展開群組；完整電路與判斷沒有改變。'); return; } setSelected(id); setInspectorPage('summary'); if (matchMedia('(max-width: 1050px)').matches) setInspectorOpen(true); }
  function loadArtifact(a: RunArtifact) { setArtifact(a); setParent(a); setScenarioId(a.scenarioId ?? ''); setDraft({ id: a.scenarioId ?? a.runId, title: a.circuit.name, variant: 'recorded', seed: 42, circuit: a.circuit, input: a.input, evidence: a.evidence, notes: [], sourceKind: a.evidence[0]?.kind ?? 'unknown' }); setSelected(a.circuit.nodes[0]?.id ?? ''); setEvents(a.events); setReplaying(false); setPlaying(false); setChangeReason(''); setOverrides({}); setPendingConstraints(false); setTab('workbench'); setLayoutKey(k => k + 1); }
  async function run() { if (!draft || !modeAvailable || pendingConstraints) return; await guarded(async () => { if (parent && !changeReason.trim()) throw new Error('請填寫本次修改／重跑原因，原執行將保留。'); const validation = await api<{ valid: boolean; errors: unknown[] }>('/validate', { circuit: draft.circuit }); if (!validation.valid) throw new Error(`電路無效：${pretty(validation.errors)}`); const started = await api<{ jobId: string }>('/runs', { scenarioId: draft.id, variant: draft.variant === 'recorded' ? 'normal' : draft.variant, seed: draft.seed, mode, circuit: draft.circuit, input: draft.input, evidence: draft.evidence, overrides, ...(parent ? { parentRunId: parent.runId, changeReason } : {}), budget: { maxCalls, maxNodes: Math.max(draft.circuit.nodes.length, 256), maxTimeMs, gateTimeoutMs: Math.min(maxTimeMs, 15000) } }); setArtifact(undefined); setEvents([]); setReplaying(false); setPlaying(false); setJobId(started.jobId); setRunning(true); setNotice('執行中；下方僅顯示核心實際送出的事件。'); }); }
  async function applyConstraints() { if (!draft) return; await guarded(async () => { const updated = await api<ScenarioDetail>('/scenario-preview', { scenarioId: draft.id, variant: draft.variant === 'recorded' ? 'normal' : draft.variant, seed, overrides }); setDraft(updated); setPendingConstraints(false); setLayoutKey(k => k + 1); setNotice('已由案例產生器重新計算限制與獨立求解結果。請執行電路取得新判斷；原執行保持不變。'); }); }
  async function validateAndSet(circuit: Circuit) { const r = await api<{ valid: boolean; errors: unknown[] }>('/validate', { circuit }); if (!r.valid) throw new Error(`修改未套用：${pretty(r.errors)}`); setDraft(d => d ? { ...d, circuit } : d); setNotice('修改已通過核心驗證。再次執行會建立新紀錄。'); setLayoutKey(k => k + 1); }
  function openEditor(kind: NonNullable<typeof editor>) { setEditor(kind); setEditorError(''); setEditorText(pretty(kind === 'node' ? node : kind === 'add' ? { id: `new_gate_${(draft?.circuit.nodes.length ?? 0) + 1}`, kind: 'constant', value: 'UNKNOWN' } : kind === 'input' ? draft?.input : kind === 'evidence' ? draft?.evidence : draft?.circuit)); }
  async function saveEditor() { if (!draft) return; setEditorError(''); try { const value = JSON.parse(editorText); if (editor === 'node' || editor === 'add') { const next = { ...draft.circuit, nodes: editor === 'add' ? [...draft.circuit.nodes, value as GateNode] : draft.circuit.nodes.map(n => n.id === selected ? value as GateNode : n) }; await validateAndSet(next); setSelected(value.id); } else if (editor === 'circuit') await validateAndSet(value as Circuit); else if (editor === 'input') setDraft({ ...draft, input: value as Json }); else { if (!Array.isArray(value)) throw new Error('證據必須是 EvidenceRecord 陣列。'); setDraft({ ...draft, evidence: value }); } setEditor(null); } catch (e) { setEditorError(errorMessage(e)); } }
  async function connect(source: string, target: string, remove = false) { if (!draft) return; await guarded(async () => { if (!source || !target) throw new Error('請選擇來源與目標節點。'); const next = draft.circuit.nodes.map(n => { if (n.id !== target) return n; if (n.kind === 'logic') return { ...n, inputs: remove ? n.inputs.filter(i => i !== source) : [...new Set([...n.inputs, source])] }; if (n.kind === 'semantic') return { ...n, context: remove ? (n.context ?? []).filter(i => i !== source) : [...new Set([...(n.context ?? []), source])] }; throw new Error('目標必須是程式邏輯或語意節點；固定值與精確規則不接受上游連線。'); }); await validateAndSet({ ...draft.circuit, nodes: next }); }); }
  function connectGraph(c: Connection) { if (c.source && c.target) void connect(c.source, c.target); }
  async function deleteNode() { if (!draft || !node) return; await guarded(async () => { await validateAndSet({ ...draft.circuit, nodes: draft.circuit.nodes.filter(n => n.id !== node.id), outputs: draft.circuit.outputs.filter(id => id !== node.id) }); setSelected(''); setInspectorOpen(false); }); }
  async function verify(replay = false) { if (!artifact) return; await guarded(async () => { const result = await api<{ valid: boolean; errors: string[]; result?: unknown }>(replay ? '/replay' : '/verify', { artifact }); if (!result.valid) throw new Error(result.errors.join('\n')); if (replay) { setReplaying(true); setReplayCursor(0); setPlaying(false); setNotice('離線重播已驗證：重新計算邏輯，工具僅展示已存在的回執。向後移動不會撤銷外部動作。'); } else setNotice('完整性驗證通過。雜湊只能證明內容一致，不能證明來源真實性。'); }); }
  async function importFile(file: File) { await guarded(async () => { if (file.size > 8 * 1024 * 1024) throw new Error('匯入檔案上限為 8 MiB。'); const parsed = JSON.parse(await file.text()); const result = await api<{ artifact: RunArtifact }>('/import', { artifact: parsed }); loadArtifact(result.artifact); await refreshRuns(); setNotice('匯入完成且已驗證；內容會當作資料顯示。'); }); }
  async function performance(size: number) { await guarded(async () => { const start = performanceNow(); const p = await api<ScenarioDetail>(`/performance/${size}`); setDraft(p); setArtifact(undefined); setParent(undefined); setEvents([]); setSelected(p.circuit.nodes[0]?.id ?? ''); setReplaying(false); setNodeSearch(''); setLayoutKey(k => k + 1); requestAnimationFrame(() => requestAnimationFrame(() => setPerformanceResult(`${size} 節點載入到兩個畫面更新：約 ${(performanceNow() - start).toFixed(1)} ms；${navigator.userAgent}；視窗 ${innerWidth}×${innerHeight}。包含 API 與 UI，非引擎基準。`))); }); }
  const inspector = <div className="inspector-body">{node ? <>
    <div className="inspector-title"><span className="eyebrow">{kindLabels[node.kind]} / {draft?.circuit.nodes.findIndex(n => n.id === node.id)! + 1}</span><h2>{node.id}</h2><TruthBadge truth={nodeSignal?.truth} /></div>
    <nav className="inspector-tabs" aria-label="節點檢視分頁">{[['summary', '判斷'], ['sources', '原文'], ['raw', '回應']].map(([id, title]) => <button key={id} className={inspectorPage === id ? 'active' : ''} aria-pressed={inspectorPage === id} onClick={() => setInspectorPage(id)}>{title}</button>)}</nav>
    {inspectorPage === 'summary' && <>
      <h3>有界問題</h3><p className="question">{node.kind === 'semantic' ? node.question.instructions : node.kind === 'logic' ? `${node.op.toUpperCase()} 組合上游訊號` : node.kind === 'rule' ? `檢查 ${node.path} ${node.op} ${pretty(node.value)}` : `固定真值 ${node.value}`}</p>
      <dl className="detail-list"><div><dt>執行</dt><dd><span className={`node-execution execution-${executionStates[node.id]?.state ?? 'idle'}`}>{executionStates[node.id]?.label ?? '尚未執行'}</span></dd></div><div><dt>原因</dt><dd>{decision?.reasonCode ?? nodeSignal?.reason ?? '執行後顯示可觀察的決策摘要。'}</dd></div><div><dt>提供者</dt><dd>{decision?.provider ?? '—'}</dd></div><div><dt>實際模型</dt><dd>{decision?.model ?? '未呼叫'}{decision?.upstreamModel && <small>上游：{decision.upstreamModel}</small>}</dd></div><div><dt>節點來源</dt><dd>{decision?.provenance ?? '待執行'}</dd></div></dl>
      {nodeSignal?.truth === 'UNKNOWN' && <Message kind="warning"><strong>需要補充的資料</strong><p>{unknownHelp(decision?.reasonCode ?? nodeSignal.reason)}</p></Message>}
      <h3>上游影響</h3>{dependencies(node).length ? <ul className="upstream-list">{dependencies(node).map(id => <li key={id}><button onClick={() => selectNode(id)}>{id}<TruthBadge truth={signals[id]?.truth} /></button></li>)}</ul> : <p className="muted">此節點直接讀取原始輸入，沒有上游訊號。</p>}
      {node.kind === 'semantic' && <><h3>判定政策</h3><Code value={node.policy} /><p className="fine">Noul、Choice 與 Score 保留各自數值，不合併成共同信心分數。</p></>}
      <div className="button-row"><button onClick={() => openEditor('node')} disabled={running}>編輯節點</button><button className="danger" onClick={deleteNode} disabled={running}>刪除節點</button></div><p className="fine">刪除仍被引用的節點會被核心拒絕；請先移除相關連線。</p>
    </>}
    {inspectorPage === 'sources' && <>{selectedEvidence.length ? selectedEvidence.map(e => <section className="source-excerpt" key={e.evidenceId}><span className="eyebrow">{sourceLabel[e.kind]} · {e.evidenceId}</span><blockquote>{e.citations.length ? e.citations.map(c => c.quote).join('\n') : e.content}</blockquote><p className="fine">引用位置 {e.citations.map(c => `${c.start}–${c.end}`).join(', ') || '未指定'} · {date(e.retrievedAt)}</p></section>) : <Message kind="warning">沒有可定位的來源；應補充原文與引用位置。</Message>}<p className="fine">引用存在不代表原文支持主張。此處只展示已保存的證據。</p></>}
    {inspectorPage === 'raw' && <><h3>原始判斷／分布</h3><Code value={decision?.answer ?? nodeSignal?.answer ?? null} /><h3>請求與回應</h3><Code value={activeRequest ?? null} /><p className="fine">此處是可觀察的請求與回應，不是模型內部思考。</p></>}
  </> : <div className="empty-state"><h2>選擇一個節點</h2><p>查看問題、原文、政策與判斷原因。</p></div>}</div>;

  return <div className="app-shell">
    <a className="skip-link" href="#main-content">跳至主要內容</a>
    <aside className="rail"><a className="brand" href="#main-content" aria-label="JEV Lab 首頁"><span className="brand-mark" aria-hidden="true">J</span><span>JEV<span className="brand-sub">RESEARCH LAB</span></span></a><div className="rail-label">研究工具</div><nav aria-label="主要導覽">{tabs.map(t => <button key={t.id} onClick={() => setTab(t.id)} aria-current={tab === t.id ? 'page' : undefined} className={tab === t.id ? 'active' : ''}><span>{t.num}</span>{t.label}</button>)}</nav><div className="rail-bottom"><span className="status-dot" /> 本機研究環境<br /><small>版本 0.1 · Experimental</small><p>可追溯的判斷。<br />有界的行動。</p></div></aside>
    <div className="main-shell"><header className="topbar"><span>語意邏輯研究工作台</span><div><span className="local-badge">LOCAL / LOOPBACK</span><span className="edition">研究預覽</span></div></header>
    <main id="main-content"><section className="page-heading"><div><p className="eyebrow">SEMANTIC CIRCUITS / OBSERVABLE REASONING</p><h1>{tabs.find(t => t.id === tab)?.label}<span className="heading-dot">.</span></h1><p>從問題到證據，讓每一個判斷都有跡可循。</p></div><div className="heading-note">工程流程與模型品質分開記錄。<br /><strong>範例通過不等於通用智能。</strong></div></section>
      {error && <Message kind="error"><strong>未完成操作</strong><p>{error}</p><button onClick={() => setError('')}>關閉訊息</button></Message>}
      {notice && <Message>{notice}</Message>}
      {loading && <Message>正在讀取本機案例與契約…</Message>}
      {tab === 'workbench' && <>
        <section className="scenario-strip" aria-label="情境與執行設定"><div className="section-overline">研究情境 <span>01—04</span></div><div className="scenario-options">{scenarios.map((s, i) => <button key={s.id} disabled={running} className={scenarioId === s.id ? 'selected' : ''} aria-pressed={scenarioId === s.id} onClick={() => { setScenarioId(s.id); setVariant('normal'); void loadScenario(s.id, 'normal', seed); }}><span>{String.fromCharCode(65 + i)}</span><strong>{s.title}</strong><small>{s.description}</small></button>)}</div>
          <div className="scenario-context"><span className="eyebrow">本次觀察</span><p>{Array.isArray(scenario?.learning) ? scenario.learning.join('；') : scenario?.learning ?? '選擇一個情境，開始有界的研究流程。'}</p></div>
          <div className="run-controls"><label>路徑<select value={variant} disabled={running} onChange={e => { setVariant(e.target.value); void loadScenario(scenarioId, e.target.value, seed); }}>{(scenario?.variants ?? ['normal']).map(v => <option key={v} value={v}>{variantLabel[v] ?? v}</option>)}</select></label><label>執行模式<select value={mode} disabled={running} onChange={e => setMode(e.target.value)}><option value="fixture">離線範例 · Fixture</option><option value="live-localjev">本機 LocalJev{!config?.localjev.available ? '（未設定）' : ''}</option><option value="live-typesafe">TypeSafe{!config?.typesafe.available ? '（未設定）' : ''}</option></select></label><label className="seed-field">固定種子<input type="number" value={seed} min={0} disabled={running} onChange={e => setSeed(Number(e.target.value))} onBlur={() => { if (draft && seed !== draft.seed) void loadScenario(scenarioId, variant, seed); }} /></label><button className="primary run-button" onClick={run} disabled={busy || running || loading || !draft || !modeAvailable || pendingConstraints}><span aria-hidden="true">▶</span> {running ? '執行中' : parent ? '執行新分支' : '執行電路'}</button>{running && <button onClick={() => void guarded(async () => { await api(`/jobs/${jobId}/cancel`, {}); setNotice('已送出取消要求；等待核心保存局部結果。'); })}>取消執行</button>}</div>
          {!modeAvailable && <Message kind="warning">此模型服務尚未設定。離線範例仍可操作；本次 live 推論尚未執行。</Message>}
          {mode === 'fixture' && <p className="mode-note">離線模式使用明確標示的固定回應，用於工程驗證，不代表真實模型準確率。</p>}
          {mode === 'live-localjev' && config?.localjev.available && <p className="mode-note">Bridge：{config.localjev.model} · 上游模型：{config.localjev.upstreamModel ?? '以實際回應為準'}。模型讀取合成資料時，資料仍屬合成。</p>}
          {draft && <ScenarioControls draft={draft} overrides={overrides} setOverrides={value => { setOverrides(value); setPendingConstraints(true); }} apply={() => void applyConstraints()} disabled={running || busy} />}
          {pendingConstraints && <Message kind="warning">限制已修改，請先按「套用限制／重新產生」，再執行電路。</Message>}
          {draft?.notes.length ? <div className="scenario-notes">{draft.notes.map((note, i) => <p key={i}>{note}</p>)}</div> : null}
          <details className="advanced"><summary>預算與輸入限制</summary><div className="advanced-fields"><label>最多模型呼叫<input type="number" value={maxCalls} min={0} max={64} onChange={e => setMaxCalls(Number(e.target.value))} /></label><label>總期限（毫秒）<input type="number" value={maxTimeMs} min={100} max={180000} step={1000} onChange={e => setMaxTimeMs(Number(e.target.value))} /></label><button onClick={() => openEditor('input')} disabled={!draft || running}>查看／編輯輸入</button><button onClick={() => openEditor('evidence')} disabled={!draft || running}>修改來源</button></div><p className="fine">無法取得的 token 與費用會記為 unknown。到達上限即停止新呼叫。</p></details>
          {parent && <label className="change-reason">修改／重跑原因 <span>必填 · 原 run {short(parent.runId)} 將保留</span><input value={changeReason} onChange={e => setChangeReason(e.target.value)} placeholder="例如：加入相反證據，重新檢查適用範圍" required />{isEdited && <small>有待執行修改；目前真值仍來自上一次已保存紀錄。</small>}</label>}
        </section>
        {draft && <section className="workspace-panel" aria-label="電路與節點"><div className="workspace-head"><div><span className="eyebrow">CIRCUIT / DAG</span><h2>{draft.circuit.name}</h2></div><span className="count-label">{draft.circuit.nodes.length} 節點 · {draft.circuit.outputs.length} 輸出</span></div><div className="workspace-toolbar"><label className="search-label"><span className="sr-only">搜尋節點</span><input type="search" value={nodeSearch} onChange={e => setNodeSearch(e.target.value)} placeholder="搜尋節點或問題…" /></label><button className="desktop-graph-control" onClick={() => setLayoutKey(k => k + 1)}>自動布局</button><button className="desktop-graph-control" onClick={() => setFolded(f => !f)} aria-pressed={folded}>{folded ? '展開群組' : '折疊群組'}</button><button disabled={running} onClick={() => openEditor('add')}>＋ 增加節點</button><button disabled={running} onClick={() => openEditor('circuit')}>編輯電路</button></div>
          <ScenarioObservation draft={draft} />
          <div className="workspace-grid"><div className="canvas-column"><div className="graph-canvas"><div className="canvas-caption"><span>不可變快照 · DAG</span><span>拖曳探索 / 點選檢視</span></div><Graph circuit={draft.circuit} signals={signals} executionStates={executionStates} selected={selected} onSelect={selectNode} onConnect={connectGraph} folded={folded} layoutKey={layoutKey} search={nodeSearch} /></div><div className="node-directory"><div className="directory-title"><h3>節點清單</h3><span>鍵盤可操作 · 依電路順序</span></div><ol>{visibleNodes.map((n, i) => <li key={n.id}><button className={selected === n.id ? 'selected' : ''} onClick={() => selectNode(n.id)}><span className="node-number">{String(i + 1).padStart(2, '0')}</span><span className="node-name">{n.id}<small>{kindLabels[n.kind]} · {executionStates[n.id]?.label ?? '尚未執行'}</small></span><TruthBadge truth={signals[n.id]?.truth} /></button></li>)}</ol>{!visibleNodes.length && <p className="empty-inline">沒有符合的節點。</p>}</div><details className="connection-editor"><summary>鍵盤連線工具</summary><div className="advanced-fields"><label>來源節點<select value={connectFrom} onChange={e => setConnectFrom(e.target.value)}><option value="">選擇來源</option>{draft.circuit.nodes.map(n => <option key={n.id}>{n.id}</option>)}</select></label><label>目標節點<select value={connectTo} onChange={e => setConnectTo(e.target.value)}><option value="">選擇目標</option>{draft.circuit.nodes.map(n => <option key={n.id}>{n.id}</option>)}</select></label><button disabled={busy || running} onClick={() => void connect(connectFrom, connectTo)}>建立連線</button><button disabled={busy || running} onClick={() => void connect(connectFrom, connectTo, true)}>移除連線</button></div><p className="fine">循環、失去必要輸入或不相容的連線將由核心拒絕並說明原因。</p></details></div><aside className="desktop-inspector" aria-label="節點檢視器">{inspector}</aside></div>
        </section>}
        <section className="timeline-panel"><div className="section-heading"><div><span className="eyebrow">EXECUTION TRACE</span><h2>{replaying ? '離線重播' : '執行時間軸'}</h2></div><span className={`execution-label ${running ? 'running' : ''}`}>{running ? 'RUNNING · 接收核心事件' : artifact ? workflowLabel[artifact.workflow.status] ?? artifact.workflow.status : '等待執行'}</span></div>
          {artifact && <div className="result-summary"><div><span>輸出真值</span>{Object.entries(artifact.result.outputs).map(([id, s]) => <div key={id} className="output-item"><strong>{id}</strong><TruthBadge truth={s.truth} /></div>)}</div><div><span>資料／提供者／工具</span><p>{[...new Set(artifact.evidence.map(e => sourceLabel[e.kind]))].join('、') || '未提供來源'}<br />{modeLabel[artifact.mode]}<br />{artifact.actions.length ? [...new Set(artifact.actions.map(a => a.toolKind))].join('、') : '無工具動作'}</p></div><div><span>評測</span><strong>{artifact.assessment.status === 'not_evaluated' ? '尚未評測' : artifact.assessment.status === 'passed' ? '通過既定驗收' : '驗收未通過'}</strong><small>{artifact.assessment.sampleCount} 個樣本 · {artifact.assessment.independentReview ? '有獨立覆核' : '無獨立覆核'}</small></div><div><span>本次用量</span><strong>{artifact.budget.usage.calls} 次呼叫 / {artifact.budget.usage.elapsedMs.toFixed(0)} ms</strong><small>費用 {artifact.budget.usage.costUsd === 'unknown' ? 'unknown' : `$${artifact.budget.usage.costUsd}`}</small></div></div>}
          {artifact && <div className="button-row artifact-actions"><button onClick={() => downloadArtifact(artifact)}>匯出執行包 ↓</button><button disabled={busy} onClick={() => void verify(false)}>驗證完整性</button><button disabled={busy} onClick={() => void verify(true)}>離線重播</button><button onClick={() => { setTab('compare'); setCompareId(artifact.parentRunId ?? ''); }}>比較分支</button></div>}
          {replaying && <><div className="playback-controls"><button onClick={() => { setPlaying(false); setReplayCursor(n => Math.max(0, n - 1)); }} disabled={replayCursor === 0}>← 上一步</button><button className="primary" onClick={() => { if (replayCursor >= events.length) setReplayCursor(0); setPlaying(p => !p); }}>{playing ? '暫停' : '播放紀錄'}</button><button onClick={() => { setPlaying(false); setReplayCursor(n => Math.min(events.length, n + 1)); }} disabled={replayCursor === events.length}>下一步 →</button><label className="replay-range"><span>{replayCursor} / {events.length} 事件</span><input type="range" min={0} max={events.length} value={replayCursor} onChange={e => { setPlaying(false); setReplayCursor(Number(e.target.value)); }} aria-label="重播事件位置" /></label></div><p className="fine">重播不連線模型、不再次執行工具。倒退只改變檢視位置，不撤銷動作。</p></>}
          {shownEvents.length ? <ol className="event-list">{shownEvents.map((e, i) => <li key={`${e.sequence}-${i}`}><span className="event-index">{String(e.sequence).padStart(2, '0')}</span><time>{new Date(e.at).toLocaleTimeString('zh-TW', { hour12: false })}</time><strong>{eventLabel[e.type] ?? e.type}</strong>{e.nodeId ? <button onClick={() => selectNode(e.nodeId!)}>{e.nodeId}</button> : <span className="muted">{e.requestDigest ? short(e.requestDigest) : '—'}</span>}{e.signal && <TruthBadge truth={e.signal.truth} />}</li>)}</ol> : <div className="empty-state compact"><span className="empty-symbol">◎</span><h3>{replaying ? '紀錄的起點' : '等待第一個真實事件'}</h3><p>{replaying ? '前進一步，檢查當時可觀察的狀態。' : '執行電路後，逐步顯示核心發出的事件與結果。'}</p></div>}
        </section>
        {artifact && artifact.actions.length > 0 && <section className="action-panel"><div className="section-heading"><div><span className="eyebrow">DESTINATION VERIFICATION</span><h2>沙箱動作與目的端驗證</h2></div><button disabled={busy} onClick={() => void guarded(async () => { const r = await api<{ artifact: RunArtifact }>(`/runs/${artifact.runId}/recover`, {}); loadArtifact(r.artifact); await refreshRuns(); setNotice('已查詢目的端狀態並保存新紀錄；沒有重送修復動作。'); })}>查詢 pending／復原</button></div>{artifact.actions.map(a => <div className="action-record" key={a.operationId}><strong>{a.operationId}</strong><span className="tag">{a.status}</span><span>{a.toolKind} · 動作次數 {a.executionCount ?? '未知'}</span><details><summary>回執、查詢與外部驗證</summary><Code value={a} /></details></div>)}</section>}
        {artifact && (scenarioId === 'incident' || scenarioId.toLowerCase().includes('incident') || scenarioId === 'B') && <section className="action-panel"><h2>本機模擬修復</h2><p>逾時後先保存 pending，再查詢目的端；不重送動作。</p><div className="button-row">{[['none', '執行正常修復'], ['timeout-after-apply', '注入：修復成功但回應逾時'], ['verification-failed', '注入：健康驗證失敗']].map(([fault, title]) => <button disabled={busy || artifact.actions.some(a => a.status === 'pending')} key={fault} onClick={() => void guarded(async () => { const r = await api<{ artifact: RunArtifact }>(`/runs/${artifact.runId}/action`, { kind: 'repair', fault }); loadArtifact(r.artifact); await refreshRuns(); })}>{title}</button>)}</div></section>}
        <details className="performance-tools"><summary>互動效能觀察 · 20 / 100 / 256 節點</summary><div className="button-row">{[20, 100, 256].map(n => <button key={n} disabled={busy || running} onClick={() => void performance(n)}>載入 {n} 節點</button>)}</div>{performanceResult && <p className="fine" role="status">{performanceResult}</p>}<p className="fine">替換編輯中的案例；引擎驗證不因 UI 效能而停用。</p></details>
      </>}
      {tab === 'evidence' && <section className="evidence-panel"><div className="section-heading"><div><span className="eyebrow">SOURCE REGISTER</span><h2>證據登錄表</h2></div><button onClick={() => openEditor('evidence')} disabled={!draft}>修改來源並建立分支</button></div><p className="section-description">檢查原文、取得時間、適用範圍與衝突。來源存在與主張成立是兩個不同判斷。</p>{draft?.evidence.length ? draft.evidence.map((e, i) => <article className="evidence-row" key={e.evidenceId}><div className="evidence-number">{String(i + 1).padStart(2, '0')}</div><div><div className="evidence-heading"><h3>{e.sourceId}</h3><span className="tag">{sourceLabel[e.kind]}</span></div><p>{/^https?:\/\//.test(e.locator) ? <a href={e.locator} target="_blank" rel="noreferrer">查看公開來源 ↗</a> : e.locator}</p><blockquote>{e.content}</blockquote><div className="evidence-meta"><span>取得 {date(e.retrievedAt)}</span><span>版本 {e.freshness.version ?? '未指定'}</span><span>有效至 {date(e.freshness.validUntil)}</span></div><details><summary>引用位置與適用範圍</summary><Code value={{ citations: e.citations, scope: e.scope, freshness: e.freshness, contentDigest: e.contentDigest }} /></details></div></article>) : <div className="empty-state"><h3>尚無可定位來源</h3><p>請選擇案例或匯入含原文與引用位置的執行包。</p></div>}{artifact && <><h2 className="section-title">支持、反駁與未解問題</h2><div className="claim-register">{Object.entries(artifact.signals).map(([id, signal]) => <button key={id} onClick={() => { setTab('workbench'); selectNode(id); }}><strong>{id}</strong><TruthBadge truth={signal.truth} /><p>{signal.reasonCode}</p><small>{signal.evidenceIds.join(' · ') || '沒有關聯來源'}</small></button>)}</div></>}</section>}
      {tab === 'compare' && <section className="compare-panel"><div className="section-heading"><div><span className="eyebrow">IMMUTABLE BRANCHES</span><h2>檢查修改造成的差異</h2></div></div><p className="section-description">原執行保持不變；政策、來源或人工輸入的變更記錄在新分支。單次差異不代表模型品質提升。</p><label className="compare-select">比較基準<select value={compareId || baseline?.runId || ''} onChange={e => setCompareId(e.target.value)}><option value="">選擇已保存的執行</option>{runs.filter(r => r.runId !== artifact?.runId).map(r => <option value={r.runId} key={r.runId}>{r.circuit.name} · {short(r.runId)} · {date(r.createdAt)}</option>)}</select></label>{artifact && baseline ? <><div className="comparison-grid"><RunSummary title="原方案" run={baseline} /><RunSummary title="目前分支" run={artifact} /></div><div className="table-scroll"><table><caption>節點差異</caption><thead><tr><th scope="col">節點</th><th scope="col">修改</th><th scope="col">原判斷</th><th scope="col">目前判斷</th></tr></thead><tbody>{[...new Set([...baseline.circuit.nodes.map(n => n.id), ...artifact.circuit.nodes.map(n => n.id)])].map(id => <tr key={id}><th scope="row">{id}</th><td>{pretty(baseline.circuit.nodes.find(n => n.id === id)) === pretty(artifact.circuit.nodes.find(n => n.id === id)) ? '節點未修改' : '節點已變更'}</td><td><TruthBadge truth={baseline.signals[id]?.truth} /></td><td><TruthBadge truth={artifact.signals[id]?.truth} /></td></tr>)}</tbody></table></div><details><summary>輸入與證據差異</summary><p>輸入：{pretty(baseline.input) === pretty(artifact.input) ? '相同' : '不同'} · 證據：{pretty(baseline.evidence) === pretty(artifact.evidence) ? '相同' : '不同'}</p><div className="comparison-grid"><Code value={{ input: baseline.input, evidence: baseline.evidence }} /><Code value={{ input: artifact.input, evidence: artifact.evidence }} /></div></details><Message kind="warning">資料量不足：此處僅比較兩次執行，不計算或宣稱泛化能力提升。模型品質需依獨立評測協議檢驗。</Message></> : <div className="empty-state"><h3>需要兩份已保存的執行</h3><p>先執行案例，再修改來源或政策、填寫原因並執行新分支。</p><button onClick={() => setTab('workbench')}>回到電路工作台</button></div>}</section>}
      {tab === 'library' && <section className="library-panel"><div className="section-heading"><div><span className="eyebrow">RUN ARCHIVE</span><h2>執行庫</h2></div><div className="button-row"><button disabled={busy} onClick={() => void guarded(async () => { await refreshRuns(); })}>重新整理</button><button onClick={() => fileInput.current?.click()}>匯入執行包 ↑</button><input ref={fileInput} className="sr-only" type="file" accept="application/json,.json" aria-label="匯入執行包 JSON" onChange={e => { const f = e.target.files?.[0]; if (f) void importFile(f); e.target.value = ''; }} /></div></div><label className="library-search">搜尋執行<input type="search" placeholder="名稱、run ID、模式…" value={runSearch} onChange={e => setRunSearch(e.target.value)} /></label><p className="fine">匯入會檢查版本、內容雜湊與重播一致性。檔案只作資料讀取，不執行其中的程式或命令。</p><div className="run-list">{runs.filter(r => `${r.runId} ${r.circuit.name} ${r.mode}`.toLowerCase().includes(runSearch.toLowerCase())).map(r => <article key={r.runId}><div><span className="eyebrow">{short(r.runId)} {r.parentRunId && `← ${short(r.parentRunId)}`}</span><h3>{r.circuit.name}</h3><p>{date(r.createdAt)} · {modeLabel[r.mode]} · {workflowLabel[r.workflow.status]}</p><span className="tag">Assessment: {r.assessment.status}</span>{r.actions.some(a => a.status === 'pending') && <span className="tag pending">有 pending 動作</span>}</div><div className="button-row"><button onClick={() => loadArtifact(r)}>開啟紀錄</button><button onClick={() => downloadArtifact(r)}>匯出</button></div></article>)}</div>{!runs.length && <div className="empty-state"><h3>尚無執行紀錄</h3><p>完成第一次案例後，執行包將保存在此。</p><button onClick={() => setTab('workbench')}>開始第一個案例</button></div>}</section>}
      <footer className="footer"><span>JEV LAB / 研究儀器</span><p>真值 ≠ 執行狀態 ≠ 來源真實性。模型品質未證實時，保持 experimental。</p><span>繁體中文 · v0.1</span></footer>
    </main></div>
    <Dialog open={editor !== null} onClose={() => setEditor(null)} title={editor === 'add' ? '增加節點' : editor === 'node' ? '編輯節點與政策' : editor === 'input' ? '編輯原始輸入' : editor === 'evidence' ? '編輯證據來源' : '編輯完整電路'} wide><p className="dialog-description">修改只套用到草稿。原模型輸出保持不變，下一次執行會建立新紀錄。JSON 契約由核心驗證。</p>{(editor === 'input' || editor === 'evidence' || editor === 'node') && <p className="editor-contract-note">離線範例回應只適用原始問題與來源。直接修改輸入、原文或語意題目時，服務會棄答，不能把原腳本答案當作重新推論；情境限制請使用專用控制項重新產生。人工覆核可新增固定值節點並記錄原因，不會改寫歷史模型輸出。</p>}<label className="json-editor">{editor === 'node' || editor === 'add' ? '節點 JSON' : '資料 JSON'}<textarea value={editorText} onChange={e => setEditorText(e.target.value)} spellCheck={false} aria-invalid={!!editorError} aria-describedby={editorError ? 'editor-error' : undefined} /></label>{editorError && <p id="editor-error" role="alert" className="editor-error">{editorError}</p>}<div className="dialog-actions"><button onClick={() => setEditor(null)}>取消</button><button className="primary" onClick={() => void saveEditor()}>驗證並套用</button></div></Dialog>
    <Dialog open={inspectorOpen} onClose={() => setInspectorOpen(false)} title="節點檢視器">{inspector}</Dialog>
  </div>;
}
function performanceNow() { return window.performance.now(); }
function unknownHelp(reason: string) { if (/conflict|mixed|contradict/i.test(reason)) return '目前證據互相衝突。保留支持與反駁的原文，補充適用範圍或依政策交由覆核。'; if (/stale|fresh|expir/i.test(reason)) return '資料可能過期。補上可驗證的觀察時間、有效期限與最新版本。'; if (/timeout|error|failed|budget|cancel/i.test(reason)) return '這是執行或預算問題，不能當作模型答對 UNKNOWN。檢查原始錯誤與執行限制後建立新分支。'; if (/scope|missing|evidence|insufficient/i.test(reason)) return '補充限定任務、對象、條件與指標，以及能定位的原文引用。'; return '檢查原文是否支持限定主張、必要條件是否齊全，並保留棄答原因。不要把未知視為否定。'; }
function RunSummary({ title, run }: { title: string; run: RunArtifact }) { return <article className="run-summary"><span className="eyebrow">{title}</span><h3>{short(run.runId)}</h3><p>{run.changeReason ?? '原始執行'}</p><dl className="detail-list"><div><dt>模式</dt><dd>{modeLabel[run.mode]}</dd></div><div><dt>真值輸出</dt><dd>{Object.entries(run.result.outputs).map(([id, s]) => <div key={id}>{id} <TruthBadge truth={s.truth} /></div>)}</dd></div><div><dt>未知節點</dt><dd>{Object.values(run.signals).filter(s => s.truth === 'UNKNOWN').length} / {run.circuit.nodes.length}</dd></div><div><dt>延遲</dt><dd>{run.budget.usage.elapsedMs.toFixed(0)} ms</dd></div><div><dt>費用</dt><dd>{String(run.budget.usage.costUsd)}</dd></div><div><dt>評測</dt><dd>{run.assessment.status} · n={run.assessment.sampleCount}</dd></div></dl></article>; }

function inputObject(draft: ScenarioDetail): Record<string, unknown> { return draft.input && typeof draft.input === 'object' && !Array.isArray(draft.input) ? draft.input : {}; }
function ScenarioControls({ draft, overrides, setOverrides, apply, disabled }: { draft: ScenarioDetail; overrides: Record<string, unknown>; setOverrides: (value: Record<string, unknown>) => void; apply: () => void; disabled: boolean }) {
  const input = inputObject(draft); const problem = input.problem as Record<string, unknown> | undefined;
  if (!['research', 'planning'].includes(draft.id)) return null;
  const set = (key: string, value: unknown) => setOverrides({ ...overrides, [key]: value });
  const instruments = (overrides.instruments ?? problem?.instruments ?? []) as string[];
  return <details className="scenario-constraints"><summary>{draft.id === 'planning' ? '調整探測站資源與可用儀器' : '調整研究任務與適用條件'}</summary><div className="advanced-fields">{draft.id === 'research' ? <><label>任務<select value={String(overrides.task ?? input.task ?? 'document-qa')} onChange={e => set('task', e.target.value)}><option value="document-qa">文件問答（範例範圍）</option><option value="clinical-diagnosis">臨床診斷（範圍外）</option><option value="code-generation">程式產生（範圍外）</option></select></label><label>上下文長度（tokens）<input type="number" min={1} value={Number(overrides.contextLength ?? input.contextLength ?? 32000)} onChange={e => set('contextLength', Number(e.target.value))} /></label><label>每題成本上限（合成單位）<input type="number" min={0} step={0.01} value={Number(overrides.costLimit ?? input.costLimit ?? .1)} onChange={e => set('costLimit', Number(e.target.value))} /></label></> : <><label>可用能源<input type="number" min={0} value={Number(overrides.energy ?? problem?.energy ?? 12)} onChange={e => set('energy', Number(e.target.value))} /></label><label>時間限制（分鐘）<input type="number" min={0} value={Number(overrides.minutes ?? problem?.minutes ?? 20)} onChange={e => set('minutes', Number(e.target.value))} /></label><fieldset className="instrument-checks"><legend>可用儀器</legend>{[['spectrometer', '光譜儀'], ['camera', '相機'], ['radio', '無線電']].map(([id, title]) => <label key={id}><input type="checkbox" checked={instruments.includes(id)} onChange={e => set('instruments', e.target.checked ? [...instruments, id] : instruments.filter(v => v !== id))} />{title}</label>)}</fieldset></>}<button onClick={apply} disabled={disabled}>套用限制／重新產生</button></div><p className="fine">按「套用限制」後再執行。精確限制由核心重新計算，原執行與舊計畫會保留。</p></details>;
}
function ScenarioObservation({ draft }: { draft: ScenarioDetail }) {
  const input = inputObject(draft);
  if (draft.id === 'incident') return <details className="scenario-observation" open><summary>目前觀察：日誌、指標與部署</summary><p className="observation-log">{String(input.logs ?? '未取得')}</p><p className="fine">模型假說、工具執行與健康檢查各自記錄；診斷成立不表示服務已修復。</p></details>;
  if (draft.id === 'planning') {
    const solver = input.solver as Record<string, unknown> | undefined; const verified = input.verified as Record<string, unknown> | undefined;
    return <details className="scenario-observation" open><summary>目前計畫與獨立可行性核對</summary><div className="plan-steps">{Array.isArray(input.proposal) && input.proposal.length ? input.proposal.map((step, i) => <span key={i}><b>{i + 1}</b>{String(step)}{i + 1 < (input.proposal as unknown[]).length && <i aria-hidden="true">→</i>}</span>) : <p>沒有可行的步驟序列。</p>}</div><p className="fine">求解器：{String(solver?.name ?? '—')} · 可行性：{solver?.feasible === true ? '可行' : '無解'} · 原因：{String(solver?.reason ?? '未知')} · 能源 {String(verified?.energyUsed ?? '—')} / 時間 {String(verified?.minutesUsed ?? '—')} 分鐘。</p><details><summary>資源、前置條件與驗證明細</summary><Code value={{ problem: input.problem, solver: input.solver, verified: input.verified }} /></details></details>;
  }
  if (draft.id === 'world') return <details className="scenario-observation" open><summary>目前文字世界：狀態與轉換規則</summary><div className="world-heading"><span>初始：{Array.isArray(input.initial) ? input.initial.join('、') || '觀察遮蔽／空白' : '—'}</span><span>目標：{String(input.target ?? '—')}</span><span>上限：{String(input.maxSteps ?? '—')} 步</span></div><div className="world-rules">{Array.isArray(input.rules) && input.rules.map((raw, i) => { const r = raw as Record<string, unknown>; return <div key={i}><strong>{String(r.id)}</strong><span>{Array.isArray(r.requires) ? r.requires.join(' + ') || '無必要前置' : '—'} → {Array.isArray(r.add) ? r.add.join(' + ') : '—'}</span><small>{Array.isArray(r.any) && r.any.length > 0 ? `任一：${r.any.join(' / ')}；` : ''}{Array.isArray(r.forbidden) && r.forbidden.length > 0 ? `禁止：${r.forbidden.join(', ')}；` : ''}{Array.isArray(r.remove) && r.remove.length > 0 ? `消耗：${r.remove.join(', ')}` : ''}</small></div>; })}</div><p className="fine">此處展示可見規則與初始觀察；獨立評測答案不送給規劃器。固定種子與規則家族共同決定案例。</p></details>;
  return null;
}
