import test from 'node:test';
import strict from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { ARMS,ROUTES,PROTOCOL,hash,stable,validateChoice,validateProposal,gateRoute,consensus,combine,policy,retrieve,validateDataset,publicInput,metrics,pairedDelta,shuffled } from '../research/medication/core.mjs';
import {cases,corpus} from '../research/medication/data.mjs';
import {fixtureAdapters,preflight,llmAdapter,jevAdapter} from '../research/medication/providers.mjs';
import {runArm,buildReport,verify} from '../research/medication/run.mjs';
const choice=(route='INFO',p=.9)=>({type:'choice',choice:route,probabilities:Object.fromEntries(ROUTES.map(r=>[r,r===route?p:(1-p)/4])),confidence:.8});
const proposal=(route='INFO')=>({route,change_medication:false,explanation:'Research draft only.',citations:[]});
const row=(case_id,arm='A',raw_route='INFO',repeat=0)=>({case_id,arm,mode:'live',repeat,raw_route,final_route:raw_route,errors:[],wall_ms:2,usage:null,proposal:proposal(raw_route),outputs:{}});
const metadata={mode:'fixture',arms:Object.keys(ARMS),repeats:1,seed:22,status:'completed',blockers:[]};
const c=cases[0];

test('exact requested arm matrix; only B gets retrieval',()=>{strict.deepEqual(Object.keys(ARMS),['A','B','C','D','E']);strict.deepEqual(Object.values(ARMS).map(a=>a.rag),[false,true,false,false,false]);strict.deepEqual(ARMS.E.gates,['laya','jev']);});
test('24 distinct synthetic families; no clinical labels asserted',()=>{strict.equal(validateDataset(cases,corpus).families,24);strict.equal(validateDataset(cases,corpus).clinically_reviewed,0);});
test('duplicate case IDs rejected',()=>strict.throws(()=>validateDataset([...cases,c],corpus)));
test('identical inputs under different IDs rejected',()=>strict.throws(()=>validateDataset([...cases,{...c,id:'new'}],corpus)));
test('family leakage across dev and test rejected',()=>{const d=structuredClone(cases);d[8].family=d[0].family;strict.throws(()=>validateDataset(d,corpus));});
test('non-synthetic case rejected',()=>{const d=structuredClone(cases);d[0].synthetic=false;strict.throws(()=>validateDataset(d,corpus));});
test('gold/input field leakage rejected and public input allowlisted',()=>{const d=structuredClone(cases);d[0].input.expected='INFO';strict.throws(()=>validateDataset(d,corpus));strict.deepEqual(Object.keys(publicInput(c)).sort(),['identity_confirmed','label_text','message']);});
test('invalid sources rejected',()=>{const d=structuredClone(cases);d[0].source_ids=['invented'];strict.throws(()=>validateDataset(d,corpus));});
test('retrieval returns reproducible sourced snapshots and no case labels',()=>{const docs=retrieve(c.input,corpus);strict.ok(docs.some(d=>d.id==='fda-acetaminophen'));strict.deepEqual(docs,retrieve(c.input,corpus));strict.ok(docs.every(d=>d.snapshot_hash.length===64));strict.ok(!JSON.stringify(docs).includes('expected'));});
test('unrelated retrieval query abstains rather than inventing evidence',()=>strict.deepEqual(retrieve({message:'zzzzzzzz'},corpus),[]));
test('proposal rejects unknown routes and nonboolean flags',()=>{strict.throws(()=>validateProposal({...proposal(),route:'STOP_DRUG'}));strict.throws(()=>validateProposal({...proposal(),change_medication:'false'}));});
test('proposal rejects extra fields and oversized explanations',()=>{strict.throws(()=>validateProposal({...proposal(),extra:1}));strict.throws(()=>validateProposal({...proposal(),explanation:'a'.repeat(4001)}));});
test('choice rejects NaN, null, negative and over-one probabilities',()=>{for(const p of [NaN,null,-.1,1.1]){const a=choice();a.probabilities.INFO=p;strict.throws(()=>validateChoice(a));}});
test('choice rejects missing/extra labels and nonnormalized values',()=>{const a=choice();delete a.probabilities.UNKNOWN;strict.throws(()=>validateChoice(a));const b=choice();b.probabilities.UNKNOWN=.8;strict.throws(()=>validateChoice(b));});
test('choice must agree with argmax and confidence must exist',()=>{strict.throws(()=>validateChoice({...choice(),choice:'REVIEW'}));strict.throws(()=>validateChoice({...choice(),confidence:undefined}));});
test('four-decimal SDK rounding is retained without renormalization',()=>{const a={...choice(),probabilities:{INFO:.8001,CLARIFY:.05,REVIEW:.05,EMERGENCY:.05,UNKNOWN:.05}};strict.deepEqual(validateChoice(a).probabilities,a.probabilities);});
test('low separation is UNKNOWN, never a false normal answer',()=>strict.equal(gateRoute(choice('INFO',.4)),'UNKNOWN'));
test('top-choice emergency survives low confidence threshold',()=>strict.equal(gateRoute(choice('EMERGENCY',.3)),'EMERGENCY'));
test('consensus table: any emergency wins; review veto; otherwise unanimity',()=>{for(const a of ROUTES)for(const b of ROUTES){const expected=[a,b].includes('EMERGENCY')?'EMERGENCY':[a,b].includes('REVIEW')?'REVIEW':a===b?a:'UNKNOWN';strict.equal(consensus([a,b]),expected);}});
test('consensus cannot create knowledge when models share a mistake',()=>strict.equal(consensus(['INFO','INFO']),'INFO'));
test('disagreement retains UNKNOWN and unknown is not false',()=>{strict.equal(consensus(['INFO','CLARIFY']),'UNKNOWN');strict.equal(consensus(['INFO','UNKNOWN']),'UNKNOWN');});
test('LLM emergency cannot be downgraded by decision gates',()=>strict.equal(combine('EMERGENCY',['INFO','INFO']),'EMERGENCY'));
test('single reviewer vetoes normal draft',()=>strict.equal(combine('INFO',['REVIEW']),'REVIEW'));
test('all arms use same no-autonomous-change policy',()=>strict.equal(policy(c.input,'INFO',{...proposal(),change_medication:true}).route,'REVIEW'));
test('unconfirmed identity blocks INFO but never emergency',()=>{strict.equal(policy({identity_confirmed:false},'INFO',proposal()).route,'CLARIFY');strict.equal(policy({identity_confirmed:false},'EMERGENCY',proposal()).route,'EMERGENCY');});
test('deterministic RNG and stable hash independent of object key order',()=>{strict.deepEqual(shuffled(cases,22),shuffled(cases,22));strict.equal(hash({a:1,b:2}),hash({b:2,a:1}));});
test('five-arm fixture has exact call counts and no label leakage',async()=>{for(const arm of Object.keys(ARMS)){const r=await runArm(c,arm,0,fixtureAdapters(),'fixture');strict.equal(r.attempted_calls,1+ARMS[arm].gates.length);strict.equal(r.sources.length>0,arm==='B');strict.equal(r.errors.length,0);strict.equal(r.usage,null);const requests=JSON.stringify(Object.values(r.outputs).map(v=>v.request));strict.ok(!requests.includes(c.id));strict.ok(!requests.includes('author-provisional'));strict.ok(!requests.includes('"expected"'));}});
test('parallel models receive isolated copies of the identical state',async()=>{const a=fixtureAdapters(),seen=[];a.laya=async input=>{seen.push(structuredClone(input));input.message='MUTATED';return fixtureAdapters().laya(input);};a.jev=async input=>{seen.push(structuredClone(input));return fixtureAdapters().jev(input);};await runArm(c,'E',0,a,'fixture');strict.deepEqual(seen,[c.input,c.input]);});
test('provider failure recorded and final answer escalated',async()=>{const a=fixtureAdapters();a.laya=async()=>{throw new Error('private data must not leak');};const r=await runArm(c,'C',0,a,'fixture');strict.equal(r.errors.length,1);strict.equal(r.raw_route,'UNKNOWN');strict.equal(r.final_route,'REVIEW');strict.ok(!JSON.stringify(r).includes('private data'));});
test('a surviving emergency is not suppressed when another provider fails',async()=>{const a=fixtureAdapters();a.laya=async()=>{throw Error('fail');};const old=a.jev;a.jev=async input=>({...await old(input),choice:choice('EMERGENCY')});strict.equal((await runArm(c,'E',0,a,'fixture')).final_route,'EMERGENCY');});
test('live must not accept fixture outputs',async()=>{const r=await runArm(c,'E',0,fixtureAdapters(),'live');strict.equal(r.errors.length,3);strict.equal(Object.keys(r.outputs).length,0);strict.equal(r.raw_route,'UNKNOWN');});
test('invalid gate response is a recorded failure rather than dropped case',async()=>{const a=fixtureAdapters(),old=a.laya;a.laya=async input=>({...await old(input),choice:{}});strict.equal((await runArm(c,'C',0,a,'fixture')).errors.length,1);});
test('citation presence is only an ID check, not factuality',async()=>{const a=fixtureAdapters(),old=a.llm;a.llm=async(...args)=>({...await old(...args),proposal:{...proposal(),citations:['invented']}});const r=await runArm(c,'A',0,a,'fixture');strict.equal(r.citation_id_error,true);strict.equal(r.notice.includes('Research draft'),false);});
test('empty metrics have null rates, latency, usage and cost',()=>{const m=metrics([],cases);strict.equal(m.n,0);for(const k of ['route_accuracy','emergency_recall','info_precision','input_tokens','cost_usd','latency_p95_ms'])strict.equal(m[k],null);});
test('emergency missing route counts as miss, provider failure stays denominator',()=>{const emergency=cases.find(c=>c.expected==='EMERGENCY'),r=row(emergency.id,'A','UNKNOWN');r.errors=[{role:'llm',code:'provider_failure'}];const m=metrics([r],cases);strict.equal(m.emergency_recall,0);strict.equal(m.emergency_misses,1);strict.equal(m.provider_error_rate,1);});
test('independent metric arithmetic and stage separation',()=>{const e=cases.find(c=>c.expected==='EMERGENCY');const rows=[row(c.id),row(e.id,'A','INFO')];rows[1].final_route='EMERGENCY';strict.equal(metrics(rows,cases).route_accuracy,.5);strict.equal(metrics(rows,cases,'final_route').route_accuracy,1);});
test('bootstrap pairs by case/repeat and clusters repeated families',()=>{const e=cases.find(c=>c.expected==='EMERGENCY');const rows=[row(c.id,'A'),row(c.id,'E'),row(e.id,'A','INFO'),row(e.id,'E','EMERGENCY')];const delta=pairedDelta(rows,cases,'A','E');strict.equal(delta.delta,.5);strict.equal(delta.pairs,2);strict.equal(delta.families,2);strict.deepEqual(delta,pairedDelta(rows,cases,'A','E'));strict.equal(pairedDelta(rows,cases,'A','D').delta,null);});
test('fixture report never populates live metrics or superiority claims',async()=>{const rows=[await runArm(c,'A',0,fixtureAdapters(),'fixture')];const report=buildReport(rows,[c],metadata);strict.equal(report.live_rows,0);strict.equal(report.arms.A.live_metrics,null);strict.equal(report.claims.model_superiority_established,false);strict.deepEqual(report.paired_comparisons,[]);});
test('duplicate result rows cannot inflate sample size',()=>strict.throws(()=>buildReport([row(c.id),row(c.id)],[c],{...metadata,mode:'live'})));
test('preflight names only missing settings and does not call a model',()=>{const p=preflight(['A','B','C','D','E'],{});for(const name of ['LLM_MODEL','OPENAI_API_KEY','TYPESAFE_API_KEY','JEV_MODEL'])strict.ok(p.includes(name));});
test('remote cleartext LLM endpoint rejected; loopback requires explicit model',()=>{strict.ok(preflight(['A'],{LLM_MODEL:'test',LLM_BASE_URL:'http://example.com/v1',OPENAI_API_KEY:'fake'}).length);strict.deepEqual(preflight(['A'],{LLM_MODEL:'test',LLM_BASE_URL:'http://127.0.0.1:8080/v1'}),[]);});
test('LLM adapter records request model, returned model and real usage',async()=>{let body;const fetcher=async(url,options)=>{body=JSON.parse(options.body);return new Response(JSON.stringify({model:'returned-model',choices:[{finish_reason:'stop',message:{content:JSON.stringify(proposal())}}],usage:{prompt_tokens:12,completion_tokens:6}}));};const out=await llmAdapter({LLM_MODEL:'requested-model'},fetcher)(c.input,[]);strict.equal(body.messages.length,2);strict.equal(body.store,false);strict.equal(out.model,'returned-model');strict.deepEqual(out.usage,{input_tokens:12,output_tokens:6});});
test('LLM refusals/truncations and credential echoes are not valid outputs',async()=>{for(const raw of [{model:'m',choices:[{finish_reason:'length',message:{content:'{}'}}]},{model:'m',choices:[],echo:'TOPSECRET'}]){await strict.rejects(llmAdapter({LLM_MODEL:'m',OPENAI_API_KEY:'TOPSECRET'},async()=>new Response(JSON.stringify(raw)))(c.input,[]));}});
test('TypeSafe bridge uses core Provider.evaluate contract and no invented usage',async()=>{let seen;const out=await jevAdapter({evaluate:async(state,questions)=>{seen={state,questions};return{model:'official-jev-test',answers:{route:choice()}};}})(c.input);strict.equal(seen.questions.route.type,'choice');strict.deepEqual(seen.state,c.input);strict.equal(out.provider,'typesafe');strict.equal(out.usage,null);});
test('CLI fixture, offline verification, collision, tamper and blocked live receipts',()=>{
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'jev-med-')),out=path.join(tmp,'fixture'),script=new URL('../research/medication/run.mjs',import.meta.url);
 try{
  execFileSync(process.execPath,[script.pathname,'--mode','fixture','--out',out],{stdio:'pipe'});
  strict.equal(verify(out).rows,120);
  strict.notEqual(spawnSync(process.execPath,[script.pathname,'--out',out]).status,0);
  fs.appendFileSync(path.join(out,'summary.md'),'tampered');strict.throws(()=>verify(out));
  const blocked=path.join(tmp,'blocked');const r=spawnSync(process.execPath,[script.pathname,'--mode','live','--allow-live','--out',blocked],{env:{PATH:process.env.PATH},encoding:'utf8'});
  strict.equal(r.status,2);strict.equal(verify(blocked).status,'blocked');strict.equal(verify(blocked).rows,0);
 }finally{fs.rmSync(tmp,{recursive:true,force:true});}
});
test('CLI enforces bounded calls and explicit live consent',()=>{const script=new URL('../research/medication/run.mjs',import.meta.url).pathname;strict.notEqual(spawnSync(process.execPath,[script,'--mode','live','--out','/unused']).status,0);strict.notEqual(spawnSync(process.execPath,[script,'--max-calls','1','--out','/unused']).status,0);});
