import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, BusFront, CarFront, Check, ChevronRight, CircleHelp, GitBranch, Play, RefreshCw, Square, Timer } from 'lucide-react';
import { compareEtaSession, aggregateEtaComparisons } from '../server/eta-comparison-core.mjs';
import type { EtaSession, EtaPrediction } from '../server/eta-comparison-core.mjs';
import './compare.css';

type Scenario = { id: string; kind: 'car' | 'bus_wait'; title: string; description: string; origin?: { name: string; lat: number; lng: number }; destination?: { name: string; lat: number; lng: number }; bus?: { query: string; routeName: string; direction: string } };
type Observation = { provider: string; status: string; quantity: string; valueSeconds: number | null; distanceMeters?: number; sourceUpdatedAt?: string | null; fetchedAt?: string | null; timestampMeaning?: string; reason?: string; message?: string; stopId?: string; routeId?: string; direction?: string; detail?: string; bus?: { stopId: string; routeId: string; direction: string; stopName: string; routeName: string; destination: string } };
type Capture = { scenario: Scenario; observedAt: string; observations: Observation[]; googleMapsUrl: string; bus?: { stopId: string; routeId: string; direction: string }; metrics: Record<string, number>; warnings?: string[] };
type Entry = { session: EtaSession; title: string; googleSource: string; startedAt?: string; locked?: boolean };
async function api<T>(path: string, body?: unknown, signal?: AbortSignal): Promise<T> { const r = await fetch(`/api/compare/${path}`, { ...(body === undefined ? {} : { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }), signal }); const data = await r.json(); if (!r.ok) throw new Error(typeof data.error === 'string' ? data.error : '無法完成本次比較'); return data; }
const minutes = (seconds: number) => `${Math.round(seconds / 6) / 10}`;
const when = (v?: string | null) => v && Number.isFinite(Date.parse(v)) ? new Date(v).toLocaleTimeString('zh-TW', { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }) : '未提供';
const nowIso = () => new Date().toISOString();
const object = (v: unknown): Record<string, unknown> => v !== null && typeof v === 'object' ? v as Record<string, unknown> : {};
const rangeText = (value: unknown) => { const r = object(value); const min = Number(r.min), max = Number(r.max); return Number.isFinite(min) && Number.isFinite(max) ? min === max ? minutes(min) : `${minutes(min)}–${minutes(max)}` : '—'; };
const statusText = (provider: string) => provider === 'osrm' ? '道路模型估時・不含即時車流' : provider.includes('google') ? 'Google Routes API・非Google Maps App畫面' : '台北市官方到站預估';
export default function CompareApp() {
  const [scenarios, setScenarios] = useState<Scenario[]>([]); const [selected, setSelected] = useState(''); const [configured, setConfigured] = useState(false); const [capture, setCapture] = useState<Capture | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [googleMin, setGoogleMin] = useState(''); const [googleMax, setGoogleMax] = useState(''); const [confirmed, setConfirmed] = useState(false); const [googleMode, setGoogleMode] = useState('unknown'); const [entries, setEntries] = useState<Entry[]>([]); const [focusId, setFocusId] = useState<string | null>(null); const [clock, setClock] = useState(Date.now()); const [actualConfirmed, setActualConfirmed] = useState(false);
  const controller = useRef<AbortController | null>(null); const generation = useRef(0);
  useEffect(() => { document.title = '時間比較 · JEV Maps'; const c = new AbortController(); api<{ scenarios: Scenario[]; google: { configured: boolean } }>('config', undefined, c.signal).then(r => { setScenarios(r.scenarios); setConfigured(r.google.configured); const requested = new URLSearchParams(location.search).get('scenario'); setSelected(r.scenarios.find(s => s.id === requested)?.id || r.scenarios[0]?.id || ''); }).catch(e => { if (!c.signal.aborted) setError(e.message); }); const timer = setInterval(() => setClock(Date.now()), 1000); return () => { c.abort(); controller.current?.abort(); clearInterval(timer); }; }, []);
  const scenario = scenarios.find(s => s.id === selected); const local = capture?.observations.find(o => !o.provider.toLowerCase().includes('google')); const google = capture?.observations.find(o => o.provider.toLowerCase().includes('google'));
  const active = entries.find(e => e.session.id === focusId); const comparison = active ? compareEtaSession(active.session, { now: clock }) : null;
  const cohortKind = scenario?.kind === 'car' ? 'DRIVE_TRIP' : 'BUS_WAIT'; const cohortSource = active?.googleSource || [...entries].reverse().find(e => e.session.scenario.kind === cohortKind)?.googleSource;
  const aggregate = useMemo(() => aggregateEtaComparisons(entries.filter(e => e.session.scenario.kind === cohortKind && e.googleSource === cohortSource).map(e => e.session), { now: clock }), [entries, clock, cohortKind, cohortSource]);
  const change = (id: string) => { generation.current++; controller.current?.abort(); setBusy(false); setSelected(id); setCapture(null); setGoogleMin(''); setGoogleMax(''); setGoogleMode('unknown'); setConfirmed(false); setFocusId(null); setError(''); setActualConfirmed(false); };
  async function observe() { if (!scenario) return; controller.current?.abort(); const c = new AbortController(); controller.current = c; const id = ++generation.current; setBusy(true); setError(''); setCapture(null); setFocusId(null); setGoogleMin(''); setGoogleMax(''); setGoogleMode('unknown'); setConfirmed(false); setActualConfirmed(false); const timeout = setTimeout(() => c.abort(), 30000);
    try { const r = await api<Capture>('observe', { scenarioId: scenario.id }, c.signal); if (id !== generation.current) return; setCapture(r); if (!r.observations.some(o => !o.provider.includes('google') && typeof o.valueSeconds === 'number')) setError('本次沒有有效的本地預估；請查看來源狀態，不會以示範數字補上。'); }
    catch (e) { if (id === generation.current) setError(c.signal.aborted ? '本次查詢已停止，請重試。' : (e as Error).message); }
    finally { clearTimeout(timeout); if (id === generation.current) setBusy(false); }
  }
  const available = typeof local?.valueSeconds === 'number' && local.valueSeconds >= 0;
  const automaticGoogle = typeof google?.valueSeconds === 'number' && google.valueSeconds >= 0;
  const captureOld = !capture || clock - Date.parse(capture.observedAt) > 120000 || clock < Date.parse(capture.observedAt);
  function makePair() {
    if (!capture || !scenario || !local || !available || captureOld) return;
    const min = automaticGoogle ? google!.valueSeconds! : Number(googleMin) * 60; const max = automaticGoogle ? min : googleMax.trim() ? Number(googleMax) * 60 : min;
    if (!Number.isFinite(min) || !Number.isFinite(max) || min < 0 || max < min || max > 86400 || (!automaticGoogle && (!confirmed || !googleMin.trim() || googleMode === 'scheduled'))) { setError('請填有效分鐘，並確認 Google 顯示的是同一種時間；班表不納入本輪即時預估比較。'); return; }
    const at = nowIso(); const referenceAt = capture.observedAt; const kind = scenario.kind === 'car' ? 'DRIVE_TRIP' : 'BUS_WAIT';
    const context = kind === 'DRIVE_TRIP' ? { originKey: `${scenario.origin!.lat},${scenario.origin!.lng}`, destinationKey: `${scenario.destination!.lat},${scenario.destination!.lng}`, departureAt: at } : { stopId: local.bus?.stopId || capture.bus?.stopId || '', routeId: local.bus?.routeId || capture.bus?.routeId || '', direction: local.bus?.direction || capture.bus?.direction || scenario.bus!.direction, referenceAt };
    const localPrediction: EtaPrediction = { kind, context, basis: 'live', capturedAt: local.fetchedAt || capture.observedAt, sourceTimestamp: { at: local.sourceUpdatedAt || local.fetchedAt || capture.observedAt, basis: kind === 'BUS_WAIT' ? 'provider_updated' : 'response_observed' }, estimate: { minSeconds: local.valueSeconds!, maxSeconds: local.valueSeconds! }, precision: 'seconds' };
    const googlePrediction: EtaPrediction = { kind, context: { ...context }, basis: 'live', capturedAt: automaticGoogle ? google!.fetchedAt || capture.observedAt : at, sourceTimestamp: { at: automaticGoogle ? google!.sourceUpdatedAt || google!.fetchedAt || capture.observedAt : at, basis: automaticGoogle ? 'response_observed' : 'manual_display_observed' }, estimate: { minSeconds: min, maxSeconds: max }, precision: automaticGoogle ? 'seconds' : min === max ? 'rounded_minutes' : 'reported_interval' };
    const session: EtaSession = { id: `${scenario.id}-${Date.now()}`, scenario: { id: scenario.id, label: scenario.title, kind, routeAlignment: 'unverified' }, local: localPrediction, google: googlePrediction };
    setEntries(old => [...old.slice(-23), { session, title: scenario.title, googleSource: automaticGoogle ? 'Google Routes API' : `Google Maps 畫面觀察 · ${googleMode === 'live' ? '即時標示' : '更新方式未標示'}` }]); setFocusId(session.id); setClock(Date.now()); setError(''); setActualConfirmed(false);
  }
  function start() { if (!active || active.locked) return; const at = nowIso(); if (comparison?.status !== 'comparable' || Date.now() - Math.min(Date.parse(active.session.local.capturedAt), Date.parse(active.session.google.capturedAt)) > 120000) { setError('預估已超過兩分鐘，請重新查詢再開始實測。'); return; }
    setEntries(all => all.map(entry => { if (entry.session.id !== active.session.id) return entry; const session = structuredClone(entry.session); if (session.scenario.kind === 'DRIVE_TRIP') { session.local.context.departureAt = at; session.google.context.departureAt = at; } else { session.local.context.referenceAt = at; session.google.context.referenceAt = at; } return { ...entry, session, startedAt: at, locked: true }; })); setActualConfirmed(false); setClock(Date.now()); setError(''); }
  function finish() { if (!active?.startedAt || !actualConfirmed) return; const at = nowIso(); setClock(Date.now()); setEntries(all => all.map(entry => entry.session.id !== active.session.id ? entry : { ...entry, session: { ...entry.session, actual: { kind: entry.session.scenario.kind, context: { ...entry.session.local.context }, basis: 'live', startedAt: entry.startedAt!, completedAt: at, recordedAt: at, source: 'manual_observation', selfReported: true, ...(entry.session.scenario.kind === 'DRIVE_TRIP' ? { samePathConfirmed: true } : { nextVehicleConfirmed: true }) } } })); }
  const delta = comparison ? object(comparison.comparison) : {}; const deltaRange = object(delta.signedDeltaRangeSeconds); const comparable = typeof deltaRange.min === 'number';
  const statsLocal = aggregate.metrics.local; const statsGoogle = aggregate.metrics.google;
  return <main className="ec-app"><header className="ec-top"><a href="/delivery/bus"><ArrowLeft size={17} />返回地圖</a><span><GitBranch size={19} /><strong>JEV Maps</strong><i />時間比較</span><a href="/delivery">汽車路線<ArrowUpRight size={14} /></a></header>
    <div className="ec-layout"><aside className="ec-sidebar"><span className="ec-eyebrow">比較情境</span>{(['car','bus_wait'] as const).map(kind => <section key={kind}><h2>{kind === 'car' ? <CarFront size={16} /> : <BusFront size={16} />}{kind === 'car' ? '汽車全程時間' : '公車等候時間'}</h2>{scenarios.filter(s => s.kind === kind).map(s => <button className={s.id === selected ? 'selected' : ''} key={s.id} onClick={() => change(s.id)}><span>{s.title}</span><ChevronRight size={15} /></button>)}</section>)}<p className="ec-side-note">同一種時間才能相比。<br />「等車」不等於「整段搭乘」。</p></aside>
      <article className="ec-main"><div className="ec-title"><span className="ec-eyebrow">ESTIMATE COMPARISON</span><h1>兩個預估，差多久？</h1><p>先看差異，再用實際抵達檢驗準確度。</p></div>
        <section className="ec-scenario"><div><span>{scenario?.kind === 'car' ? <CarFront size={20} /> : <BusFront size={20} />}</span><div><h2>{scenario?.title || '正在載入情境'}</h2><p>{scenario?.description}</p></div></div><button className="ec-primary" disabled={busy || !scenario} onClick={() => void observe()}><RefreshCw size={16} className={busy ? 'ec-spin' : ''} />{busy ? '正在取得預估…' : '查詢本情境'}</button></section>
        {error && <p className="ec-error" role="alert"><CircleHelp size={17} />{error}</p>}
        <p className="ec-snapshot">{active ? `已凍結的觀察快照 · ${when(active.session.local.capturedAt)}，不會自動更新` : capture ? `本輪查詢 · ${when(capture.observedAt)}，兩分鐘內完成配對` : '手動查詢一次，不會在背景呼叫 Google'}</p><div className="ec-estimates"><section><span className="ec-label">本頁採用的預估</span><div className="ec-number">{active ? <><strong>{minutes(active.session.local.estimate.minSeconds)}</strong><span>分鐘</span></> : available ? <><strong>{minutes(local!.valueSeconds!)}</strong><span>分鐘</span></> : <strong>—</strong>}</div><p>{local ? statusText(local.provider) : scenario?.kind === 'bus_wait' ? '台北市官方公車預估' : 'OSRM道路模型估時'}</p><small>{active ? `快照取得 ${when(active.session.local.capturedAt)}` : local ? `資料 ${when(local.sourceUpdatedAt)} · 取得 ${when(local.fetchedAt)}` : '查詢後顯示來源與時間'}</small>{local && !available && <p className="ec-inline-warning">{local.detail || local.reason || local.message || '來源目前沒有有效預估'}</p>}</section>
          <section className="ec-google"><span className="ec-label">{active?.googleSource === 'Google Routes API' || automaticGoogle ? 'Google Routes API' : 'Google Maps'}</span><div className="ec-number">{active ? <><strong>{minutes(active.session.google.estimate.minSeconds)}{active.session.google.estimate.maxSeconds !== active.session.google.estimate.minSeconds ? `–${minutes(active.session.google.estimate.maxSeconds)}` : ''}</strong><span>分鐘</span></> : automaticGoogle ? <><strong>{minutes(google!.valueSeconds!)}</strong><span>分鐘</span></> : <strong>—</strong>}</div><p>{active ? active.googleSource : automaticGoogle ? '官方API結果，可能與Maps App不同' : '讀取同情境的畫面預估'}</p>{active ? <small>快照取得 {when(active.session.google.capturedAt)}</small> : capture ? <a href={capture.googleMapsUrl} target="_blank" rel="noreferrer">開啟 Google Maps<ArrowUpRight size={14} /></a> : <small>{configured ? '汽車查詢會同時呼叫Google Routes API' : '未連接Google API，可記錄畫面觀察值'}</small>}</section></div>
        {capture && !active && <section className="ec-reference"><div className="ec-section-heading"><h2>{automaticGoogle ? '建立本輪比較' : '記下 Google Maps 顯示的時間'}</h2><span>只保留於此分頁</span></div>{!automaticGoogle && <><p>{scenario?.kind === 'bus_wait' ? '請打開同一站牌、同一路線與方向，查看下一班「還要等多久」。不要填整段搭車時間。' : '使用相同起終點、開車模式與立即出發，記下建議路線的預估。'}</p>{local?.bus && <p className="ec-bus-match"><strong>{local.bus.stopName} · {local.bus.routeName}</strong><span>往 {local.bus.destination} · {local.bus.direction === '0' ? '去程' : '返程'}</span></p>}<div className="ec-inputs"><label>預估分鐘<input type="number" min="0" max="1440" step="0.1" value={googleMin} onChange={e => setGoogleMin(e.target.value)} placeholder="例如 15" /></label><label>若顯示區間，上限<input type="number" min="0" max="1440" step="0.1" value={googleMax} onChange={e => setGoogleMax(e.target.value)} placeholder="單一數字可留空" /></label><label>畫面資訊<select value={googleMode} onChange={e => setGoogleMode(e.target.value)}><option value="unknown">未標示更新方式</option><option value="live">有即時／目前路況標示</option><option value="scheduled">只有時刻表</option></select></label></div><label className="ec-confirm"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />我已核對同起終點／站牌、方向與交通模式，剛看到這個數字。</label></>}{captureOld && <p className="ec-inline-warning">本輪查詢已超過2分鐘，請重新查詢以便配對。</p>}<button className="ec-primary" disabled={!available || captureOld || !automaticGoogle && (!confirmed || !googleMin.trim() || googleMode === 'scheduled')} onClick={makePair}><Check size={16} />比較這一輪</button></section>}
        {active && <section className="ec-result"><div className="ec-section-heading"><h2>本輪時間差</h2><span>{when(active.session.local.capturedAt)} / {when(active.session.google.capturedAt)}</span></div>{comparable ? <><div className="ec-delta"><strong>約 {rangeText(deltaRange)}</strong><span>分鐘</span><p>本頁預估 − Google；負值代表本頁估得較短。</p></div><div className="ec-bars">{[{name:'本頁',p:active.session.local},{name:active.googleSource,p:active.session.google}].map((x,i) => <div key={i}><span>{x.name}</span><div><i style={{width:`${Math.max(3,x.p.estimate.maxSeconds/Math.max(active.session.local.estimate.maxSeconds,active.session.google.estimate.maxSeconds,1)*100)}%`}} /></div><b>{minutes(x.p.estimate.minSeconds)}{x.p.estimate.maxSeconds !== x.p.estimate.minSeconds ? `–${minutes(x.p.estimate.maxSeconds)}` : ''} 分</b></div>)}</div><p className="ec-caption">{scenario?.kind === 'bus_wait' ? '時間差已換算到共同等待起點；圖表保留各來源當時的原始預估。' : '相同起終點的建議路線可能不同，這不是同一條道路的準確度結論；估得較短不代表實際更快。'} Google畫面分鐘可能經過取整。</p></> : <p className="ec-inline-warning">本輪無法公平配對：{(comparison?.reasons || []).join('；')}</p>}
          <div className="ec-measure"><div><Timer size={19} /><div><strong>{active.session.actual ? '實際抵達已記錄' : active.startedAt ? '實測計時中' : '誰比較準？等實際抵達再判斷。'}</strong><p>{active.session.actual ? '這是使用者自行觀察的紀錄，尚未經獨立覆核。' : active.startedAt ? `已經過 ${minutes(Math.max(0,(clock-Date.parse(active.startedAt))/1000))} 分鐘；不要把測試點擊當真實抵達。` : '現在真的要出發或在站牌候車時，再開始記錄。'}</p></div></div>{!active.startedAt ? <button disabled={!comparable} onClick={start}><Play size={15} />開始實測</button> : !active.session.actual ? <div className="ec-finish"><label><input type="checkbox" checked={actualConfirmed} onChange={e => setActualConfirmed(e.target.checked)} />{active.session.scenario.kind === 'BUS_WAIT' ? '我觀察到相同路線、方向的下一班車到站' : '我已抵達，且兩個預估與實際走的是同一條路線'}</label><button disabled={!actualConfirmed} onClick={finish}><Square size={14} />記錄實際抵達</button></div> : <span className="ec-recorded"><Check size={16} />已記錄</span>}</div>
        </section>}
        <section className="ec-history"><div className="ec-section-heading"><h2>多情境比較</h2><span>{entries.length} 輪紀錄</span></div><div className="ec-table-scroll"><table><thead><tr><th>情境</th><th>本頁預估</th><th>Google預估</th><th>時間差</th><th>實際／準確度</th></tr></thead><tbody>{entries.length ? entries.map(entry => { const r = compareEtaSession(entry.session,{now:clock}); const d = object(r.comparison); return <tr key={entry.session.id}><td><button onClick={() => { change(entry.session.scenario.id); setFocusId(entry.session.id); }}>{entry.title}</button><small>{when(entry.session.local.capturedAt)} · {entry.googleSource}</small></td><td>{minutes(entry.session.local.estimate.minSeconds)} 分</td><td>{minutes(entry.session.google.estimate.minSeconds)}{entry.session.google.estimate.maxSeconds !== entry.session.google.estimate.minSeconds ? `–${minutes(entry.session.google.estimate.maxSeconds)}` : ''} 分</td><td>約 {rangeText(d.signedDeltaRangeSeconds)} 分</td><td>{entry.session.actual ? r.accuracy.status === 'eligible' ? `實際 ${minutes(r.accuracy.actualSeconds!)} 分；誤差 ${rangeText(r.accuracy.localErrorRangeSeconds)} / ${rangeText(r.accuracy.googleErrorRangeSeconds)} 分` : '紀錄不符配對條件' : entry.startedAt ? '實測中' : '待實測'}</td></tr>; }) : <tr><td colSpan={5} className="ec-table-empty">先選一個情境，完成同一輪的兩個預估。</td></tr>}</tbody></table></div>
          <p className="ec-cohort">準確度統計：{cohortKind === 'DRIVE_TRIP' ? '汽車全程' : '公車候車'} · {cohortSource || '尚無 Google 觀察'}（{aggregate.sessionCount} 輪）</p><div className="ec-score-strip"><div><span>可評估的實際紀錄</span><strong>{aggregate.eligibleAccuracyCount}<small> 筆</small></strong></div><div><span>本頁平均絕對誤差</span><strong>{rangeText(statsLocal.meanAbsoluteErrorRangeSeconds)}<small> 分鐘</small></strong></div><div><span>Google平均絕對誤差</span><strong>{rangeText(statsGoogle.meanAbsoluteErrorRangeSeconds)}<small> 分鐘</small></strong></div></div><p className="ec-caption">90%樣本的誤差上限：本頁 {rangeText(statsLocal.p90AbsoluteErrorRangeSeconds)} 分鐘 ／ Google {rangeText(statsGoogle.p90AbsoluteErrorRangeSeconds)} 分鐘。</p><p className="ec-caption">沒有實際抵達就不計準確度。汽車與候車、不同Google來源不應合併宣稱勝負；小樣本只供檢查，不代表泛化效果。</p>
        </section><details className="ec-method"><summary><CircleHelp size={16} />比較方法與限制</summary><p>兩筆預估需同一交通目的，來源與取得時間落在120秒範圍內；Google畫面未提供來源更新時間時，僅是當時的畫面觀察。公車以來源時間加等待秒數，對齊到共同等待起點。Google區間保留區間，不取中點。</p><p>實測先凍結預估，再記錄出發／候車與抵達。公車需確認同站同線同方向下一班；汽車需確認兩個預估與實際路徑相同。這是自行觀察資料，不是GPS驗證。無資料、過期或方向不符均不當成0分鐘。</p><p>本頁不以Google為真實答案，不呼叫語意模型修改ETA。這裡比較的是OSRM／官方公車來源，尚不是「JEV提升預測準確率」的證據。Google來源只保留於此分頁記憶體，重整後清除；沒有持久化或匯出。最多保留24輪。</p><a href="https://developers.google.com/maps/documentation/routes/policies" target="_blank" rel="noreferrer">Google Maps 資料政策<ArrowUpRight size={13} /></a></details>
      </article></div></main>;
}
