import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowUpRight, ChevronRight, Info, RefreshCw, X } from 'lucide-react';
type Observation = { id: string; name: string; speedKph: number | null; congestionLabel: string; distanceMeters: number; matchLabel: string };
type Traffic = { status: string; observations: Observation[]; freshness: { state: string; sourceUpdatedAt: string | null; ageSeconds: number | null; maxAgeSeconds: number }; provenance: { fetchedAt?: string; sourceUrl?: string; measurement?: string; timeBasis?: string } };
export default function TrafficPanel({ coordinates, version, mode, stale }: { coordinates: [number, number][]; version?: string; mode: string; stale: boolean }) {
  const [data, setData] = useState<Traffic | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [clock, setClock] = useState(Date.now()); const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { const update = () => setClock(Date.now()); const timer = setInterval(update, 5000); document.addEventListener('visibilitychange', update); return () => { clearInterval(timer); document.removeEventListener('visibilitychange', update); }; }, []);
  useEffect(() => {
    setData(null); setError(''); if (mode !== 'live' || stale) { setBusy(false); return; } const c = new AbortController(); let disposed = false; setBusy(true); const timer = setTimeout(() => c.abort(), 15000);
    const stride = Math.max(1, Math.ceil(coordinates.length / 1800)); const points = coordinates.filter((_, i) => i % stride === 0 || i === coordinates.length - 1);
    fetch('/api/traffic/nearby', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ coordinates: points }), signal: c.signal }).then(async response => { const r = await response.json(); if (!response.ok) throw new Error(typeof r.error === 'string' ? r.error : '道路速度暫時無法取得'); if (!disposed && !c.signal.aborted) { setData(r); setClock(Date.now()); } }).catch(e => { if (!disposed) setError(c.signal.aborted ? '道路速度查詢逾時，請重新規劃後再試。' : e.message); }).finally(() => { clearTimeout(timer); if (!disposed) setBusy(false); });
    return () => { disposed = true; clearTimeout(timer); c.abort(); };
  }, [coordinates, version, mode, stale]);
  const age = data?.freshness.sourceUpdatedAt ? (clock - Date.parse(data.freshness.sourceUpdatedAt)) / 1000 : NaN;
  const fresh = data?.freshness.state === 'fresh' && Number.isFinite(age) && age >= 0 && age <= 120 && !stale;
  if (mode !== 'live') return null;
  return <><button className="rm-events-row rm-traffic-row" onClick={() => dialog.current?.showModal()}><span>{busy ? <RefreshCw className="rm-spin" size={17} /> : <Activity size={17} />}附近路段速度</span><span>{busy ? '查詢中' : fresh ? `來源 ${Math.floor(age)} 秒前` : '待更新'}<ChevronRight size={16} /></span></button>
    <dialog className="rm-dialog" ref={dialog} aria-labelledby="rm-traffic-title" onClick={e => { if (e.target === dialog.current) dialog.current.close(); }}><header><div><span className="rm-eyebrow">TAIPEI ROAD SPEED</span><h2 id="rm-traffic-title">附近路段速度</h2></div><button className="rm-icon-button" aria-label="關閉道路速度" onClick={() => dialog.current?.close()}><X size={22} /></button></header><div className="rm-dialog-body"><p className="rm-event-intro">官方路段速度是平滑5分鐘平均。來源時間是資料交換時間，沒有每台感測器的觀測時間；附近路段不一定是本趟行車道路，這些速度尚未用於修改路線或到達估時。</p>
      {busy ? <p role="status">正在查看官方道路速度…</p> : !fresh ? <div className="rm-events-empty"><Info size={28} /><strong>沒有符合時效的道路速度</strong><p>{error || '來源超過120秒、時間不明或暫時不可用，已隱藏速度數字。'}</p></div> : <><div className="rm-speed-stamp"><span className="rm-pulse" />來源 {Math.floor(age)} 秒前交換<p>{new Date(data!.freshness.sourceUpdatedAt!).toLocaleString('zh-TW', { hour12: false })} · 超過120秒即隱藏</p></div>{data!.observations.length ? data!.observations.map(o => <article className="rm-speed-item" key={o.id}><div><strong>{o.name}</strong><p>{o.congestionLabel} · 約距路線 {Math.round(o.distanceMeters)} 公尺</p></div><span>{o.speedKph === null ? '無資料' : <><b>{Math.round(o.speedKph)}</b><small>km/h</small></>}</span></article>) : <p>這條候選路線附近沒有可列出的觀測，不代表道路暢通。</p>}<p className="rm-time-note">最多列出5個附近路段；以概略起終點比對，非完整道路匹配。</p></>}
      <a className="rm-speed-source" href="https://data.taipei/dataset/detail?id=b5aaf33a-a6dc-4836-bce6-09986241fe11" target="_blank" rel="noreferrer">臺北市道路速率資料集<ArrowUpRight size={13} /></a><p className="rm-time-note">重新規劃或下一次自動查看時會同步查詢；資料取得時間：{data?.provenance.fetchedAt ? new Date(data.provenance.fetchedAt).toLocaleString('zh-TW', { hour12: false }) : '未取得'}。</p></div></dialog></>;
}
